const GET_USER_ALL = 'GET_USER_ALL';
const GET_USER_ALL_PENDING = 'GET_USER_ALL_PENDING';
const GET_USER_ALL_FULFILLED = 'GET_USER_ALL_FULFILLED';
const GET_USER_ALL_REJECTED = 'GET_USER_ALL_REJECTED';
const RESET_USER = 'RESET_USER';
export {
  GET_USER_ALL,
  GET_USER_ALL_PENDING,
  GET_USER_ALL_FULFILLED,
  GET_USER_ALL_REJECTED,
  RESET_USER,
};
