// ==================== USER =====================
const GET_USER_ALL = 'GET_USER_ALL';
const GET_USER_ALL_PENDING = 'GET_USER_ALL_PENDING';
const GET_USER_ALL_FULFILLED = 'GET_USER_ALL_FULFILLED';
const GET_USER_ALL_REJECTED = 'GET_USER_ALL_REJECTED';

const GET_USER_BY_ID = 'GET_USER_BY_ID';
const GET_USER_BY_ID_PENDING = 'GET_USER_BY_ID_PENDING';
const GET_USER_BY_ID_FULFILLED = 'GET_USER_BY_ID_FULFILLED';
const GET_USER_BY_ID_REJECTED = 'GET_USER_BY_ID_REJECTED';

const POST_USER = 'POST_USER';
const POST_USER_PENDING = 'POST_USER_PENDING';
const POST_USER_FULFILLED = 'POST_USER_FULFILLED';
const POST_USER_REJECTED = 'POST_USER_REJECTED';

const DELETE_USER = 'DELETE_USER';
const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';
const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';

const PUT_USER = 'PUT_USER';
const PUT_USER_PENDING = 'PUT_USER_PENDING';
const PUT_USER_FULFILLED = 'PUT_USER_FULFILLED';
const PUT_USER_REJECTED = 'PUT_USER_REJECTED';

const RESET_USER = 'RESET_USER';
//================================================

// ==================== UMKM =====================
const GET_UMKM_ALL = 'GET_UMKM_ALL';
const GET_UMKM_ALL_PENDING = 'GET_UMKM_ALL_PENDING';
const GET_UMKM_ALL_FULFILLED = 'GET_UMKM_ALL_FULFILLED';
const GET_UMKM_ALL_REJECTED = 'GET_UMKM_ALL_REJECTED';

const GET_UMKM_BY_ID = 'GET_UMKM_BY_ID';
const GET_UMKM_BY_ID_PENDING = 'GET_UMKM_BY_ID_PENDING';
const GET_UMKM_BY_ID_FULFILLED = 'GET_UMKM_BY_ID_FULFILLED';
const GET_UMKM_BY_ID_REJECTED = 'GET_UMKM_BY_ID_REJECTED';

const POST_UMKM = 'POST_UMKM';
const POST_UMKM_PENDING = 'POST_UMKM_PENDING';
const POST_UMKM_FULFILLED = 'POST_UMKM_FULFILLED';
const POST_UMKM_REJECTED = 'POST_UMKM_REJECTED';

const DELETE_UMKM = 'DELETE_UMKM';
const DELETE_UMKM_PENDING = 'DELETE_UMKM_PENDING';
const DELETE_UMKM_FULFILLED = 'DELETE_UMKM_FULFILLED';
const DELETE_UMKM_REJECTED = 'DELETE_UMKM_REJECTED';

const PUT_UMKM = 'PUT_UMKM';
const PUT_UMKM_PENDING = 'PUT_UMKM_PENDING';
const PUT_UMKM_FULFILLED = 'PUT_UMKM_FULFILLED';
const PUT_UMKM_REJECTED = 'PUT_UMKM_REJECTED';

const RESET_UMKM = 'RESET_UMKM';
//================================================
export {
  //USER
  DELETE_USER,
  DELETE_USER_PENDING,
  DELETE_USER_FULFILLED,
  DELETE_USER_REJECTED,
  PUT_USER,
  PUT_USER_PENDING,
  PUT_USER_FULFILLED,
  PUT_USER_REJECTED,
  GET_USER_BY_ID,
  GET_USER_BY_ID_PENDING,
  GET_USER_BY_ID_FULFILLED,
  GET_USER_BY_ID_REJECTED,
  POST_USER,
  POST_USER_PENDING,
  POST_USER_FULFILLED,
  POST_USER_REJECTED,
  GET_USER_ALL,
  GET_USER_ALL_PENDING,
  GET_USER_ALL_FULFILLED,
  GET_USER_ALL_REJECTED,
  RESET_USER,
  //USER
  //UMKM
  GET_UMKM_BY_ID,
  GET_UMKM_BY_ID_PENDING,
  GET_UMKM_BY_ID_FULFILLED,
  GET_UMKM_BY_ID_REJECTED,
  POST_UMKM,
  POST_UMKM_PENDING,
  POST_UMKM_FULFILLED,
  POST_UMKM_REJECTED,
  DELETE_UMKM,
  DELETE_UMKM_PENDING,
  DELETE_UMKM_FULFILLED,
  DELETE_UMKM_REJECTED,
  PUT_UMKM,
  PUT_UMKM_PENDING,
  PUT_UMKM_FULFILLED,
  PUT_UMKM_REJECTED,
  GET_UMKM_ALL,
  GET_UMKM_ALL_PENDING,
  GET_UMKM_ALL_FULFILLED,
  GET_UMKM_ALL_REJECTED,
  RESET_UMKM,
  //UMKM
};
